name: build

on:
  push:
    branches:
      - main
    paths: 
      - 'Project/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - main
    paths: 
      - 'Project/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Action
        run: |
          echo "Download 4D app"

          echo "Download Builder app"
          git clone  --branch v1 https://github.com/mesopelagique/build-action.git -o $(pwd)/Compiler
          # curl -L https://github.com/mesopelagique/build-action/releases/latest/download/build-action.zip --output build-action.zip


