name: build

on:
  push:
    branches:
      - main
    paths: 
      - 'Project/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - main
    paths: 
      - 'Project/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Action
        run: |
          workingDir=$(mktemp -d -t ci-XXXXXXXXXX)
          
          echo "📦 Download Builder app"
          # git clone  --branch v1 https://github.com/mesopelagique/build-action.git -o $workingDir 
          curl -L https://github.com/mesopelagique/build-action/releases/download/0.0.1/Compilator.zip --output build-action.zip
          unzip -qq build-action.zip -d $workingDir
          workingDir="$workingDir/Compilator.4dbase"

          echo "🟦 Download 4D app"
          curl ${{ secrets.SERVER_URL }} -o 4DServer.zip
          unzip -qq 4DServer.zip -d $workingDir
          rm -f 4DServer.zip
          
          #find $workingDir
          ls $workingDir/tool4d.app/Contents/MacOS/4D
          compiler="$workingDir/4D.app/Contents/MacOS/4D"
          if [ ! -d "$compiler" ]; then
            compiler="$workingDir/tool4d.app/Contents/MacOS/4D"
          fi
          if [ ! -d "$compiler" ]; then
            compiler="$workingDir/4D Server.app/Contents/MacOS/4D Server"
          fi
          echo $compiler

          echo "🧸 Launch entrypoint"
          chmod +x $workingDir/entrypoint.sh
          # $workingDir/entrypoint.sh "project file" "release or not as 1 or 0" "compilation options"
          $workingDir/entrypoint.sh "Project/BuildSuccess.4DProject" "" ""
