name: buildWithParams

on:
  push:
    branches:
      - main
    paths: 
      - 'Resources/warning/Project/**'
      - '.github/workflows/params.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Action
        uses: mesopelagique/build-action@v1
        with:
          file: "Resources/warning/Project/warning.4DProject"
