name: release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and release action   
        run: |
          project="Project/BuildSuccess.4DProject" # if empty will launch a find and the first will be used
          failedOnWarning=1 # default is true/1
          compilationOptions="" # for instance {\"typeInference\": \"none\"} 
          curl -fsSL https://raw.githubusercontent.com/mesopelagique/build-action/main/run.sh | bash -s ${{ secrets.SERVER_URL }} "$project" $failedOnWarning "$compilationOptions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          RELEASE: 1
